language: python
python:
  - "2.7"
  - "2.6"
before_install:
  - sudo add-apt-repository http://ppa.launchpad.net/ubuntugis/ppa/ubuntu -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgdal-dev
install:
  - "pip install -r libre/requirements.txt --use-mirrors"
  - "pip install coveralls"
notifications:
  email: false
script:
  - python manage.py test data_drivers origins
  - coverage run --source=data_drivers,origins manage.py test data_drivers origins
after_success:
  - coveralls
